spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    kubecost:
      repoURL: https://kubecost.github.io/cost-analyzer/
      chart: kubecost/cost-analyzer
      targetRevision: "1.101.1"
    nginx:
      repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: "4.1.4"
    prometheus:
      repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-community/kube-prometheus-stack
      targetRevision: "45.7.1"
    trivy:
      repoURL: https://aquasecurity.github.io/helm-charts/
      chart: aqua/trivy-operator
      targetRevision: "0.12.1"