spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    kubecost:
      repoURL: https://kubecost.github.io/cost-analyzer/
      chart: cost-analyzer
      targetRevision: "1.101.1"
    nginx:
      repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: "4.1.4"
    prometheus:
      repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "45.7.1"
    trivy:
      repoURL: https://aquasecurity.github.io/helm-charts/
      chart: trivy-operator
      targetRevision: "0.12.1"
    argocd:
      repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: "5.26.1"
